### ISSUE TITLE
Change Foundry doc section to reflect the instruction given

### ISSUE THREAD

**Issue by kingzamzon** [kaiachain/kaia-docs#160]
**Describe the content contribution you'd suggest**
The current [Deploy Smart Contract Using Foundry](https://docs.kaia.io/build/smart-contracts/deploy/foundry/) section of the docs the images still shows klaytn instead of kaia. 

I have created the whole process again, I want to update to the images and link to the smart contract example on Kaia Kairos testnet

**Comment by CoderOfPHCity** [comment]
Please assign to me , I have done similar
