### ISSUE TITLE
Update Hardhat Contract Verification Guide Screenshot to Match New Kaiascope UI

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/kaia-docs#164]
**Describe the content contribution you'd suggest**

The current documentation in the [hardhat contract verification](https://docs.kaia.io/build/smart-contracts/verify/hardhat/#kairos) section contains outdated screenshots from Klaytnscope. This needs to be updated to reflect the latest Kaiascope UI changes.

**Tasks**
* Replace existing screenshots in the hardhat contract verification section with current Kaiascope UI images
* Ensure all steps in the verification process are accurately represented

**Comment by IbrahimIjai** [comment]
Okay, I am taking this one
