### ISSUE TITLE
Update Fee Delegation Guide Screenshot to Match New Kaiascope UI

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/kaia-docs#166]
**Describe the content contribution you'd suggest**

The current documentation in the [fee delegation guide](https://docs.kaia.io/build/tutorials/fee-delegation-example/#44-kaia-scope-) section contains outdated screenshots from Klaytnscope. This needs to be updated to reflect the latest Kaiascope UI changes.

**Tasks**
* Replace existing screenshots in the fee delegation section with current Kaiascope UI images
* Ensure all steps in the process are accurately represented

**Comment by FrankiePower** [comment]
Please can you assign this to me?
