### ISSUE TITLE
Update Build a dApp using Scaffold-ETH guide Screenshot to Match New Kaiascope UI

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/kaia-docs#167]
**Describe the content contribution you'd suggest**

The current documentation in the [Build a dApp using Scaffold-ETH guide](https://docs.kaia.io/build/tutorials/scaffold-eth/#verify-your-deployed-contract-) section contains outdated screenshots from Klaytnscope. This needs to be updated to reflect the latest Kaiascope UI changes.

**Tasks**
* Replace existing screenshots in the Build a dApp using Scaffold-ETH section with current Kaiascope UI images
* Ensure all steps in the verification process are accurately represented

**Comment by FrankiePower** [comment]
i can do this too!

**Comment by CoderOfPHCity** [comment]
Please assign to me

**Comment by ayo-klaytn** [comment]
You can proceed to work on this issue @CoderOfPHCity

**Comment by CoderOfPHCity** [comment]
https://github.com/CoderOfPHCity/kaia-docs/blob/main/docs/build/tutorials/scaffold-eth.md

**Comment by Belloabraham121** [comment]
@ayo-klaytn I’ve previously built a project with scaffold-eth  and I would like to work on this issue if this issue is still available.
