### ISSUE TITLE
Update Screenshots on Kaia - Safepal guide 

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/kaia-docs#168]
**Describe the content contribution you'd suggest**

The current screenshots in the [Kaia - Safepal guide](https://docs.kaia.io/build/tools/wallets/safepal-s1/#adding-kaia-native-coin-) has Klaytn logo.

**Tasks**
* Remove Klaytn logo from the screenshots  / add Kaia logo instead. 
* Ensure all steps in the process are accurately represented

**Comment by FrankiePower** [comment]
also this!

**Comment by sogobanwo** [comment]
I would love to work on this.

**Comment by ayo-klaytn** [comment]
Kindly proceed to work on the issue @sogobanwo
