### ISSUE TITLE
Update Screenshots in Kaiascope guide to reflect New Kaiascope UI

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/kaia-docs#169]
**Describe the content contribution you'd suggest**

The current documentation in the [Kaiascope](https://docs.kaia.io/build/tools/block-explorers/kaiascope/) section contains outdated screenshots from Klaytnscope. This needs to be updated to reflect the latest Kaiascope UI changes.

**Tasks**
* Replace existing screenshots in the section with current Kaiascope UI images
* Ensure all steps in the process are accurately represented

**Comment by kingzamzon** [comment]
I will love to work on this

**Comment by Bukola-tech** [comment]
I would like to contribute by addressing this issue. I can update the Kaiascope section by replacing the outdated Klaytnscope screenshots with accurate images of the latest Kaiascope UI. I will also ensure the steps are thoroughly reviewed and correctly aligned with the updated UI.

Let me know if I can proceed with this task.

**Comment by ayo-klaytn** [comment]
Kindly proceed with the task @Bukola-tech
